enum ContestantStatus { active, eliminated }

class Contestant {
  final String? contestantId; // ID is now optional and handled by the data layer
  final String name;
  final String? photoUrl; // photoUrl is now optional
  final ContestantStatus status;

  Contestant({
    this.contestantId, // ID is optional, will be generated by data layer
    required this.name,
    this.photoUrl, // photoUrl is optional
    required this.status,
  });
}
