class Gala {
  final String? galaId; // ID is now optional and handled by the data layer
  final int galaNumber;
  final DateTime date;
  final List<String> nominatedContestants;
  final Map<String, dynamic> results;

  Gala({
    this.galaId, // ID is optional, will be generated by data layer
    required this.galaNumber,
    required this.date,
    required this.nominatedContestants,
    required this.results,
  });
}
