import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:porrot_2025/data/repositories/gala_repository_impl.dart';
import 'package:porrot_2025/data/repositories/prediction_repository_impl.dart';
import 'package:porrot_2025/domain/entities/gala.dart';
import 'package:porrot_2025/domain/usecases/create_gala_usecase.dart';
import 'package:porrot_2025/domain/usecases/get_prediction_count_for_gala_usecase.dart';
import 'package:porrot_2025/presentation/screens/admin_gala_results_screen.dart';
import 'package:porrot_2025/presentation/widgets/admin/nominee_selection_widget.dart';

class GalaManager extends StatefulWidget {
  const GalaManager({super.key});

  @override
  State<GalaManager> createState() => _GalaManagerState();
}

class _GalaManagerState extends State<GalaManager> {
  final _formKey = GlobalKey<FormState>();
  final _galaNumberController = TextEditingController();
  List<Gala> _galas = [];
  bool _isLoading = true;

  late final CreateGalaUseCase _createGalaUseCase;
  late final GetPredictionCountForGalaUseCase _getPredictionCountForGalaUseCase;
  late final GalaRepositoryImpl _galaRepository;

  @override
  void initState() {
    super.initState();
    // In a real app, use dependency injection
    _galaRepository = GalaRepositoryImpl(FirebaseFirestore.instance);
    final predictionRepository = PredictionRepositoryImpl(
      FirebaseFirestore.instance,
    );
    _createGalaUseCase = CreateGalaUseCase(_galaRepository);
    _getPredictionCountForGalaUseCase = GetPredictionCountForGalaUseCase(
      predictionRepository,
    );
    _loadGalas();
  }

  Future<void> _loadGalas() async {
    try {
      final galas = await _galaRepository.getAllGalas();
      setState(() {
        _galas = galas;
        _isLoading = false;
      });
    } catch (e) {
      setState(() {
        _isLoading = false;
      });
      if (mounted) {
        // Fix context issue
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Failed to load galas: $e')));
      }
    }
  }

  void _saveGala() async {
    if (_formKey.currentState!.validate()) {
      final scaffoldMessenger = ScaffoldMessenger.of(context);
      final gala = Gala(
        // galaId is null - will be auto-generated by the data layer
        galaNumber: int.parse(_galaNumberController.text),
        date: DateTime.now(), // Defaulting date, can be changed later
        nominatedContestants: [], // Empty for now
        results: {}, // Empty for now
      );

      try {
        final newGalaId = await _createGalaUseCase.execute(gala);
        scaffoldMessenger.showSnackBar(
          const SnackBar(content: Text('Gala created successfully!')),
        );
        _formKey.currentState!.reset();
        _galaNumberController.clear();
        // Refresh the list of galas
        _loadGalas();
        _showNomineeSelectionDialog(newGalaId);
      } catch (e) {
        scaffoldMessenger.showSnackBar(
          SnackBar(content: Text('Failed to create gala: $e')),
        );
      }
    }
  }

  void _showNomineeSelectionDialog(String galaId) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return NomineeSelectionWidget(galaId: galaId);
      },
    ).then((_) => _loadGalas());
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Manage Galas',
                  style: Theme.of(context).textTheme.headlineSmall,
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _galaNumberController,
                  decoration: const InputDecoration(labelText: 'Gala Number'),
                  keyboardType: TextInputType.number,
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please enter a gala number';
                    }
                    if (int.tryParse(value) == null) {
                      return 'Please enter a valid number';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 24),
                ElevatedButton(
                  onPressed: _saveGala,
                  child: const Text('Create Gala'),
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),
          Text(
            'Existing Galas',
            style: Theme.of(context).textTheme.headlineSmall,
          ),
          const SizedBox(height: 16),
          if (_isLoading)
            const Center(child: CircularProgressIndicator())
          else if (_galas.isEmpty)
            const Text('No galas found.')
          else
            ListView.builder(
              shrinkWrap: true,
              physics:
                  const NeverScrollableScrollPhysics(), // To work inside SingleChildScrollView
              itemCount: _galas.length,
              itemBuilder: (context, index) {
                final gala = _galas[index];
                return Card(
                  child: ListTile(
                    title: Text('Gala ${gala.galaNumber}'),
                    subtitle: Text(
                      'Date: ${gala.date.toString()} | '
                      'ID: ${gala.galaId ?? "Auto-generated"}',
                    ),
                    trailing: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        FutureBuilder<int>(
                          future: _getPredictionCount(gala.galaId!),
                          builder: (context, snapshot) {
                            if (snapshot.connectionState ==
                                ConnectionState.waiting) {
                              return const CircularProgressIndicator();
                            }
                            if (snapshot.hasError) {
                              return const Text('Error');
                            }
                            return Text(
                              '${snapshot.data} votes',
                              style: const TextStyle(color: Colors.grey),
                            );
                          },
                        ),
                        IconButton(
                          icon: const Icon(Icons.people),
                          onPressed: () =>
                              _showNomineeSelectionDialog(gala.galaId!),
                        ),
                        IconButton(
                          icon: const Icon(Icons.edit),
                          onPressed: () {
                            Navigator.of(context).push(
                              MaterialPageRoute(
                                builder: (context) =>
                                    AdminGalaResultsScreen(gala: gala),
                              ),
                            );
                          },
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
        ],
      ),
    );
  }

  Future<int> _getPredictionCount(String galaId) async {
    return _getPredictionCountForGalaUseCase.execute(galaId);
  }

  @override
  void dispose() {
    _galaNumberController.dispose();
    super.dispose();
  }
}
